name: Publish Python Package
on:
  release:
    types: [ created ]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/simple-video-utils
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Update version in pyproject.toml
        run: sed -i "s/^version = .*/version = \"${GITHUB_REF_NAME}\"/" pyproject.toml

      - name: Install build dependencies
        run: pip install build

      - name: Build a binary wheel dist
        run: |
          rm -rf dist
          python -m build

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
